### ISSUE TITLE
Using Kerguelen data in a PHD thesis

### ISSUE THREAD

**Issue by ebocher** [seeschloss/kerguelen#1]
Hi,
First of all, thanks a lot to share your data viz build on top of D3JS. I'm contacting you because we will be interested to use the geojson data. The kerguelen git repo is yet available with  a nice WTFPL license ;-)
Can I use the geojson data with the same licence ?
Cheers

**Comment by seeschloss** [comment]
Hi, the copyright status of this data is unclear as I didn't digitize it myself, and the original book isn't in the public domain either to begin with.

So I'm afraid I cannot place it myself under the WTFPL (I probably shouldn't even have included it in the repo?) but as far as I'm concerned, you can use it however you want ;-)

**Comment by ebocher** [comment]
Thanks
Do you know where the data comes from?

**Comment by seeschloss** [comment]
I sent you an email explaining it: it was scraped from a now-disappeared website (kerguelen-voyages.com, still available on archive.org and I also still have the raw scraped data that I can send you if you'd like, it also contains the "explications" for places that have them).

I can only assume that they did the digitization themselves, but in any case I'm not legitimate to place this data myself under any kind of permissive license.

There's also this PDF http://ssz.fr/brdl/Toponymie%20des%20Terres%20Australes.pdf that I made from the scanned pages, with a quick automated OCR that was not very usable in my case but might help you.

**Comment by seeschloss** [comment]
Not sure if you actually received my email with the data and sources but if you need more info you can open this issue again.
